#pragma once

/**
@file
Subclass of CDCM6208_CONTROL, which is generated by wxFormBuilder.
*/

#include "CDCM6208_GUI.h"
#include "lime/LimeSuite.h"

class CDCM6208 : public CDCM6208_CONTROL
{

public:
   /** Constructor */
   CDCM6208( wxWindow* parent );
   CDCM6208(  wxWindow* parent, wxWindowID id , const wxString& title , const wxPoint& pos , const wxSize& size , long style );
     virtual void Initialize(lms_device_t* pCtrPort);
protected:
     lms_device_t* device;



};
